# Generated by Django 2.2.5 on 2021-05-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20210531_0020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rule',
            new_name='HouseRule',
        ),
        migrations.AddField(
            model_name='room',
            name='house_rules',
            field=models.ManyToManyField(to='rooms.HouseRule'),
        ),
    ]
